# Import env
spring.config.import=optional:file:.env[.properties]
# Application
spring.application.name=ROOMLY
spring.application.version=1.0.0
server.port=8080
server.address=0.0.0.0
# Avatars & colors
avatar.storage.path=./src/main/java/org/roomly/assets/avatars
colors.storage.path=./src/main/java/org/roomly/assets/colors
colors.storage.filename=colors_catalog.json
avatar.storage.filename=avatars_catalog.json
#Database
#! Now using H2 in-memory database for testing purposes, to be replaced with PostgreSQL in production

# JWT
security.jwt.refresh.token.expiration=2592000000
security.jwt.access.token.expiration=3600000
security.jwt.secret=${JWT_SECRET_KEY}
# External API
external.api.openfoodfacts.url=https://world.openfoodfacts.org/api/v0/product

#========= TEMP =========
# For testing purposes only, to be removed in production

spring.datasource.url=jdbc:h2:mem:roomlydb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop