# === DATABASE CONFIGURATION (Docker Compose run) ===
spring.datasource.url=${DB_URL:jdbc:postgresql://${POSTGRES_HOST:postgres}:5432/${POSTGRES_DB:roomlydb}}
spring.datasource.username=${POSTGRES_USER:${POSTGRESS_USER:roomly}}
spring.datasource.password=${POSTGRES_PASSWORD:${POSTGRESS_PASSWORD:roomly}}
spring.datasource.driver-class-name=org.postgresql.Driver

