# === IMPORT ENVIRONMENT VARIABLES ===
spring.config.import=optional:file:.env[.properties]
# === APPLICATION CONFIGURATION ===
spring.application.name=ROOMLY
spring.application.version=1.0.0
spring.profiles.default=local
server.port=8080
server.address=0.0.0.0
# === AVATARS AND COLORS STORAGE ===
avatar.storage.path=${AVATAR_STORAGE_PATH:./src/main/java/org/roomly/assets/avatars}
colors.storage.path=${COLORS_STORAGE_PATH:./src/main/java/org/roomly/assets/colors}
colors.storage.filename=colors_catalog.json
avatar.storage.filename=avatars_catalog.json
# === DATABASE CONFIGURATION (shared) ===
spring.jpa.hibernate.ddl-auto=update
# === JWT CONFIGURATION ===
security.jwt.refresh.token.expiration=2592000000
security.jwt.access.token.expiration=3600000
security.jwt.secret=${JWT_SECRET_KEY}
# === EXTERNAL API CONFIGURATION ===
external.api.openfoodfacts.url=https://world.openfoodfacts.org/api/v0/product

# === SPRING BOOT ADMIN CONFIGURATION ===
spring.boot.admin.client.instance.management-base-url=http://localhost:8080
spring.boot.admin.client.url=http://localhost:8080
management.endpoints.web.exposure.include=health,info,metrics,env,loggers,threaddump,heapdump
management.endpoint.health.show-details=always
spring.boot.admin.client.instance.name=ROOMLY
spring.boot.admin.client.instance.metadata.user.name=a
spring.boot.admin.client.instance.metadata.user.password=a